name: CI to Docker Hub

# Déclencheur : quand tu pousses du code sur la branche main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Se connecter à Docker Hub avec tes secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construire et envoyer l'image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          # C'est ici qu'on adapte le chemin vers ton backend
          context: "./src/backend"
          # On pousse l'image sur DockerHub
          push: true
          # Le nom complet de ton image
          tags: ctessier/frigoapplication:latest
